zarrs/zarrs

CHANGELOG.md
examples/http_array_read.rs
examples/sharded_array_write_read.rs
examples/zip_array_write_read.rs
src/array/array_async_readable.rs
src/array/array_async_readable_writable.rs
src/array/array_async_writable.rs
src/array/array_sync_readable.rs
src/array/array_sync_readable_writable.rs
src/array/array_sync_writable.rs
src/array/codec.rs
src/group.rs
src/storage.rs
src/storage/storage_handle.rs
src/storage/storage_transformer.rs
src/storage/storage_transformer/performance_metrics.rs
src/storage/storage_transformer/storage_transformer_chain.rs
src/storage/storage_transformer/usage_log.rs

This is mostly an internal change, but downstream users may need to:
- `Arc` wrap storage transformers
- In methods generic over storage, add a `'static` lifetime to storage

Refactor storage types

---

CHANGELOG.md
examples/array_write_read.rs
examples/async_array_write_read.rs
examples/rectangular_array_write_read.rs
examples/sharded_array_write_read.rs
examples/zip_array_write_read.rs
src/array/array_builder.rs
src/array/dimension_name.rs

This makes `DimensionName::new()` and `ArrayBuilder::dimension_names()` generic over their inputs.
Can now write
```rust
ArrayBuilder::new(...).dimension_names(["y", "x"].into())
```
instead of
```rust
ArrayBuilder::new(...).dimension_names(vec!["y".into(), "x".into()].into())
```

Dimension names cleanup

---

CHANGELOG.md
examples/array_write_read.rs
src/storage.rs
src/storage/storage_async.rs
src/storage/storage_sync.rs
src/storage/store.rs

- Remove unused `storage::store::{Readable,Writable,ReadableWritable,Listable}Store`
- Add `{Async}ReadableWritableListableStorageTraits` and `{Async}ReadableWritableListableStorage`

Storage cleanup

---

CHANGELOG.md
src/node.rs
src/node/node_metadata.rs

Feature requested in #12 
Changes:
- implement three getter methods for the `zarrs::Node` struct
```rust
/// Returns a reference to the path of the node.
#[must_use] 
pub fn path(&self) -> &NodePath {
&self.path
}
/// Returns a reference to the metadata of the node.
#[must_use]
pub fn metadata(&self) -> &NodeMetadata {
&self.metadata
}
/// Returns a reference to the metadata of the node.
#[must_use]
pub fn children(&self) -> &Vec<Node> {
&self.children
}
```
- Derived clone traits for `zarrs::Node` and `zarrs::node::NodeMetadata`

Add public getters for Node properties 

---

CHANGELOG.md
src/array/codec/array_to_bytes/zfp.rs
src/array/codec/array_to_bytes/zfp/zfp_array.rs
src/array/codec/array_to_bytes/zfp/zfp_codec.rs
src/array/codec/array_to_bytes/zfp/zfp_field.rs
src/array/codec/array_to_bytes/zfp/zfp_partial_decoder.rs

Support 8/16-bit integer types with the zfp codec through promotion to 32-bit in accordance with the [zfp utility functions](https://zfp.readthedocs.io/en/release1.0.1/low-level-api.html#utility-functions).

Support 8 and 16 bit integer data types with zfp codec

---

CHANGELOG.md
src/array_subset.rs
src/array_subset/iterators.rs
src/array_subset/iterators/chunks_iterator.rs
src/array_subset/iterators/indices_iterator.rs
src/array_subset/iterators/linearised_indices_iterator.rs

`Indices::new_with_start_end` now takes a `std::ops::Range` rather than a `start` and `end`
Change internal structure of various iterators to use `std::ops::Range` and remove redundant `length`

Iterator improvements

---

CHANGELOG.md
src/storage/storage_async.rs
src/storage/storage_sync.rs
src/storage/store/store_async.rs
src/storage/store/store_sync.rs
src/storage/store/store_sync/memory_store.rs

- Expand `set_partial_values` tests
- Specialise `set_partial_values` for `MemoryStore`
- `[async_]store_set_partial_values` no longer truncates
- this could corrupt values depending on the order of `set_partial_values` calls

`set_partial_values` improvements

---

src/storage/storage_handle.rs
src/storage/storage_sync.rs
src/storage/storage_transformer/performance_metrics.rs
src/storage/storage_transformer/usage_log.rs
src/storage/store/store_sync/filesystem_store.rs
src/storage/store/store_sync/memory_store.rs
src/storage/store/store_sync/opendal.rs
tests/array_async_to_sync.rs

Closes #54 
As suggested, I added `ReadableWritableStorageTraits` to the default `storage_sync` implementation so that anything implementing `ReadableStorageTraits` and `WritableStorageTraits` will have this trait as well. I also added a simple test for an async storage adapter to check that it is readable and writable.
One potential issue with this approach is that it removes some of the custom commented mutex handling code in the various implementations. I'm not sure the use for that commented code. Do you think that will be a problem?
I'm happy to take a different approach here if necessary.

Add `ReadableWritableStorageTraits` automatically for all implementations

---

src/storage.rs

`StoreKeysPrefixes` is returned by `ListableStorageTraits::list_dir`, but it can't be constructed outside of `zarrs`. This adds a pub constructor.

Make `StoreKeysPrefixes` constructible

---

src/array/chunk_cache/chunk_cache_lru.rs

`std::mem::size_of` is not in the prelude of the MSRV

---

Cargo.toml
src/storage/store.rs
src/storage/store/store_sync/filesystem_store.rs

Refs #53. I've updated the example in https://github.com/LiberTEM/zarr-dio-proto/ with a case that uses this branch for writing. Let me know if a discussion directly on the PR works for you, otherwise I can move this to the issue. Performance already looks better than the buffered case:
| Method | Time (s) |
|--------- | -------- |
| Direct I/O (manual) | 6.14 |
| Direct I/O (this PR) | 17.71 |
| Buffered | 38.91s |
(performance in the buffered case also depends on if we are overwriting an existing array, in that case it takes ~51s)
An annotated flamegraph of running the example code:
From left to right:
* The leftmost `memcpy` comes from [`Bytes::from(chunk_encoded.into_owned())`](https://github.com/LDeakin/zarrs/blob/0c08caefa4b8feb723bfdcf756727576436e4962/src/array/array_sync_writable. …

Initial direct I/O support in `FilesystemStore`

---

CHANGELOG.md
src/group.rs
src/node.rs

Pending https://github.com/zarr-developers/zarr-specs/pull/292

Remove implicit group support

---

CHANGELOG.md
src/array/array_async_writable.rs
src/array/array_sync_writable.rs
src/storage/store/store_sync/filesystem_store.rs

As discussed in, and on top of, #58.
* Don't copy in `FilesystemStorage` if the `value` is already properly aligned
* Add  `Array::store_encoded_chunk`
From a first test, this hits the spot and is as fast as the manual direct I/O. Didn't profile yet. Maybe needs a companion that can tell us if the array (metadata) indicates that this method can be used.

add `Array::store_encoded_chunk`

---

CHANGELOG.md
zarrs/src/array/array_sharded_ext.rs
zarrs/src/array/array_sync_sharded_readable_ext.rs
zarrs/src/array/codec.rs
zarrs/src/array/codec/array_to_array/bitround/bitround_codec.rs
zarrs/src/array/codec/array_to_array/transpose.rs
zarrs/src/array/codec/array_to_array/transpose/transpose_codec.rs
zarrs/src/array/codec/array_to_array/transpose/transpose_partial_decoder.rs

Fixes the inner chunk grid calculation for the case where the `transpose` codec precedes `sharding_indexed`

Add `ArrayShardedExt::effective_inner_chunk_shape`

---

CHANGELOG.md
zarrs/src/array/array_async_readable.rs
zarrs/src/array/array_sync_readable.rs
zarrs/src/array/codec.rs
zarrs/src/array/codec/array_to_bytes/codec_chain.rs
zarrs/src/array/codec/array_to_bytes/sharding/sharding_codec.rs

Resolves a performance regression introduced in 0.16 when decoding sharded arrays with `Array::[async_]retrieve_array_subset_opt`.

Add `[partial_]decode_into` API

---

CHANGELOG.md
Cargo.toml
examples/array_write_read.rs
examples/array_write_read_ndarray.rs
examples/array_write_read_string.rs
examples/async_array_write_read.rs
examples/async_http_array_read.rs
examples/rectangular_array_write_read.rs
examples/sharded_array_write_read.rs
examples/sync_http_array_read.rs
examples/zip_array_write_read.rs
zarrs/doc/status/storage_transformers.md
zarrs/doc/status/stores.md
zarrs/src/array/array_builder.rs
zarrs/src/array/array_sync_sharded_readable_ext.rs
zarrs/src/array/chunk_cache/chunk_cache_lru.rs
zarrs/src/array/storage_transformer.rs
zarrs/tests/zarr_python_compat.rs
zarrs_storage/CHANGELOG.md
zarrs_storage/Cargo.toml
zarrs_storage/src/storage_adapter.rs
zarrs_storage/src/storage_adapter/performance_metrics.rs
zarrs_storage/src/storage_adapter/usage_log.rs
zarrs_storage/src/storage_async.rs

These were shoehorned in as storage transformers before storage adapters were introduced.

Change performance metrics and usage log storage transformers to storage adapters

---

CHANGELOG.md
zarrs/src/array.rs
zarrs/src/array/array_async_readable.rs
zarrs/src/array/array_async_writable.rs
zarrs/src/array/array_sync_readable.rs
zarrs/src/array/array_sync_writable.rs
zarrs/src/array/storage_transformer.rs
zarrs/src/array/storage_transformer/storage_transformer_chain.rs
zarrs/src/array/storage_transformer/storage_transformer_plugin.rs

- Add `StorageTransformerPlugin` for storage transformer registration
- Remove several `StorageTransformerExtension` trait methods no longer needed
- Change `StorageTransformerExtension::create_metadata` to return `MetadataV3` instead of an `Option`
- `StorageTransformerExtension::[async_]create_*_transformer` methods are now fallible
- `StorageTransformerExtension::async_create_*_transformer` methods are now async
- `StorageTransformerChain::from_metadata` and `try_create_storage_transformer` now has a `path: &NodePath` parameter

Storage transformer refactor

---

CHANGELOG.md
zarrs/src/node/key.rs
zarrs_storage/CHANGELOG.md
zarrs_storage/src/store_key.rs

Also validate that chunk keys do not contain '//'.

zarrs_storage: Fix `data_key` on windows

---

Cargo.toml
zarrs/Cargo.toml
zarrs/src/array/codec/array_to_bytes/sharding.rs
zarrs/src/array/codec/byte_interval_partial_decoder.rs
zarrs/src/array/codec/bytes_to_bytes/crc32c/crc32c_partial_decoder.rs
zarrs_filesystem/CHANGELOG.md
zarrs_filesystem/src/lib.rs
zarrs_http/CHANGELOG.md
zarrs_object_store/CHANGELOG.md
zarrs_opendal/CHANGELOG.md
zarrs_storage/CHANGELOG.md
zarrs_storage/Cargo.toml
zarrs_storage/src/byte_range.rs
zarrs_storage/src/store_test.rs
zarrs_zip/CHANGELOG.md

No codecs would request a footer with an offset, and most stores could not support such an operation without a size request.
- Add `ByteRange::new` and `From` for various `RangeBounds<u64>` implementors.
- Remove `ByteRange::offset()`
- Add `ByteRange::new` and `From` for `RangeBounds<u64>`

Change `ByteRange::FromEnd` to `ByteRange::Suffix`

---

CHANGELOG.md
zarrs/src/group.rs
zarrs/src/node.rs
zarrs/src/node/node_async.rs
zarrs/src/node/node_sync.rs

First draft of functions to directly get the children of a `Group`.
Not sure what the API should look like. One could also consider returning a list of `Node`s which correspond to only `Array`s/`Group`s instead of returning a list of `Array`s/`Group`s directly for the function `child_arrays`/`child_groups`, respectively.
Async function could also be added if needed.
Functions that only return a list of child names (i.e. `Vec<String>`) instead of `Array`s/`Group`s could also be useful. Something akin to  https://zarr.readthedocs.io/en/stable/api/hierarchy.html#zarr.hierarchy.Group.group_keys
Would be good to get some feedback, then I can make some further adjustments.
Disclaimer; I am still quite new to Rust.

functions to get children of Group

---

zarrs/src/group.rs
zarrs/src/node.rs

Add functions to get the `NodePath`s for the children of a `Group`.
Originally, the idea was to get the `NodeName`s. However, with the recursive option the name is ambiguous because the prefix is unknown. One consideration would be to get the relative path starting at the current `Group`, but currently there is no data structure for that and it may not be worth creating one for that use case. It would also be possible to just use a normal `String` for the relative path.
Thoughts?

Child NodePath's

---

CHANGELOG.md
Cargo.toml
zarrs/doc/status/data_types.md
zarrs/src/array/codec/array_to_bytes/bytes.rs
zarrs/src/array/data_type.rs
zarrs/src/array/element.rs
zarrs/tests/array_sync.rs
zarrs_metadata/CHANGELOG.md
zarrs_metadata/Cargo.toml
zarrs_metadata/src/v3/array/data_type.rs

refactor!: rename binary data type to bytes

---

CHANGELOG.md
zarrs/src/array/codec/array_to_bytes/pcodec/pcodec_codec.rs
zarrs_metadata/CHANGELOG.md
zarrs_metadata/src/v3/array/codec/pcodec.rs

This should be compatible with the next numcodecs release.
Fixes #111

fix: make `pcodec` compatible with `numcodecs`

---

CHANGELOG.md
zarrs/src/array.rs
zarrs/src/array/array_bytes.rs
zarrs/src/array/array_bytes/raw_bytes_offsets.rs
zarrs/src/array/codec.rs
zarrs/src/array/codec/array_to_array/transpose.rs
zarrs/src/array/codec/array_to_bytes/vlen/vlen_codec.rs
zarrs/src/array/codec/array_to_bytes/vlen_v2/vlen_v2_codec.rs
zarrs/src/array/element.rs

refactor!: change `RawBytesOffsets` into a validated newtype

---

doc/correctness_issues.md
zarrs_metadata/CHANGELOG.md
zarrs_metadata/src/v2/array.rs

It is no longer possible to create non-conformant Zarr V2 filter metadata by setting filters to `Some(Vec![])`. Zarr V2 arrays with `filters: []` can still be read. `zarr-python` also shared this bug.

fix: Zarr V2 empty filter serialisation

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
makefile
zarrs/doc/ecosystem.md
zarrs/doc/status/data_types.md
zarrs/examples/custom_data_type_fixed_size.rs
zarrs/examples/custom_data_type_variable_size.rs
zarrs/src/array.rs
zarrs/src/array/array_builder.rs
zarrs/src/array/array_errors.rs
zarrs/src/array/codec.rs
zarrs/src/array/codec/array_to_bytes/bytes/bytes_codec.rs
zarrs/src/lib.rs
zarrs_data_type/CHANGELOG.md
zarrs_data_type/Cargo.toml
zarrs_data_type/src/data_type.rs
zarrs_data_type/src/data_type_extension.rs
zarrs_data_type/src/data_type_extension_bytes_codec.rs
zarrs_data_type/src/data_type_plugin.rs
zarrs_data_type/src/lib.rs

feat: add custom data type support

---

zarrs_metadata/CHANGELOG.md
zarrs_metadata/src/v2/array/codec/blosc.rs

Changed in `numcodecs` 0.16
https://github.com/zarr-developers/numcodecs/pull/713

fix: permit (and ignore) `typesize` in `blosc` codec in Zarr V2 arrays [zarrs_metadata 0.3.x]

---

zarrs/doc/status/codecs.md
zarrs/src/array/codec/array_to_bytes/zfp.rs
zarrs_metadata/src/extension/extension_aliases_codec.rs

Pending merge of https://github.com/zarr-developers/zarr-extensions/pull/8

chore(zfp): rename from `zarrs.zfp` to `zfp`

---

CHANGELOG.md
zarrs/src/array/chunk_grid.rs
zarrs/src/array/codec/array_to_array/squeeze/squeeze_partial_decoder.rs
zarrs/src/array/codec/array_to_array/transpose/transpose_partial_decoder.rs
zarrs/src/array/codec/array_to_bytes/sharding/sharding_codec.rs
zarrs/src/array_subset.rs
zarrs/src/array_subset/iterators/chunks_iterator.rs
zarrs/src/array_subset/iterators/contiguous_indices_iterator.rs

Reduces internal allocations when creating an `ArraySubset` from ranges
Follow up to #156.

feat: Implement `From<T: IntoIterator<Item = Range<u64>>>` for `ArraySubset`

---

CHANGELOG.md
README.md
zarrs/doc/ecosystem.md
zarrs/doc/status/data_types.md
zarrs/examples/custom_data_type_fixed_size.rs
zarrs/examples/custom_data_type_float8_e3m4.rs
zarrs/examples/custom_data_type_uint12.rs
zarrs/examples/custom_data_type_uint4.rs
zarrs/examples/custom_data_type_variable_size.rs
zarrs/src/array.rs
zarrs/src/array/array_dlpack_ext.rs
zarrs/src/array/array_errors.rs
zarrs/src/array/array_representation.rs
zarrs/src/array/codec/array_to_array/fixedscaleoffset.rs
zarrs/src/array/codec/array_to_array/squeeze/squeeze_codec.rs
zarrs/src/array/codec/array_to_array/transpose/transpose_codec.rs
zarrs/src/array/codec/array_to_bytes/bytes.rs
zarrs/src/array/codec/array_to_bytes/bytes/bytes_codec.rs
zarrs/src/array/codec/array_to_bytes/packbits.rs
zarrs/src/array/data_type.rs
zarrs/src/lib.rs
zarrs_data_type/CHANGELOG.md
zarrs_data_type/src/data_type_plugin.rs
zarrs_data_type/src/fill_value.rs
zarrs_data_type/src/lib.rs

`zarrs_data_types` no longer defines data types explicitly, just the data type extension API.
This makes it more amenable to stabilisation.
`zarrs` itself can continue to evolve the `DataType` enum as new data types are created.

refactor(data_types)!: remove data type enum from `zarrs_data_types`

---

zarrs/src/group.rs
zarrs/src/node/node_name.rs
zarrs/tests/data/hierarchy.zarr/a/foo/zarr.json
zarrs/tests/hierarchy.rs

I ran into a bug in `Group::child_arrays` which was producing an invalid node path by using node.name() instead of node.path(). In adding tests for this, I realized that the `recursive` boolean wasn't doing anything since `Group::children` (and `get_child_nodes`) only use it to tell if the Node children should be populated -- neither actually returned all nodes recursively. I documented this, and removed the no-op `recursive` boolean from the various methods that had it. (The latter is a breaking change, but if anyone was passing true here, the behavior was probably already broken.) We might also consider renaming it to `populate_children` or something?
Alternatively, we could have these return all nodes/paths/arrays/groups recursively if that was the intent but then it is serving a dual …

Resolve bugs in Group::child_* methods and remove no-op `recursive` boolean

---

CHANGELOG.md
zarrs/doc/status/data_types.md
zarrs/src/array/data_type.rs
zarrs_registry/src/data_type.rs

These data types have no native Rust types, and likely won't for years (if ever).

feat: add partial support for `float8_*` data types

---

zarrs/Cargo.toml
zarrs/doc/status/data_types.md
zarrs/src/array/data_type.rs
zarrs/src/array/element.rs

Adds `Element`/`ElementOwned` implementations for the following:
- `DataType::Float8E4M3` -> `float8::F8E4M3`
- `DataType::Float8E5M2` -> `float8::F8E5M2`
- `DataType::ComplexFloat8E4M3` -> `num::complex::Complex<float8::F8E4M3>`
- `DataType::ComplexFloat8E5M2` -> `num::complex::Complex<float8::F8E5M2>`
`float8` is already out-of-date pending https://github.com/EricLBuehler/float8/pull/4 or the next `zarrs` MSRV bump

feat: add support for `float8` `Element` types

---

CHANGELOG.md
Cargo.toml
zarrs_filesystem/CHANGELOG.md
zarrs_filesystem/Cargo.toml
zarrs_http/CHANGELOG.md
zarrs_http/Cargo.toml
zarrs_object_store/CHANGELOG.md
zarrs_object_store/Cargo.toml
zarrs_opendal/CHANGELOG.md
zarrs_opendal/Cargo.toml
zarrs_storage/CHANGELOG.md
zarrs_storage/Cargo.toml
zarrs_storage/src/storage_async.rs
zarrs_storage/src/storage_sync.rs
zarrs_storage/src/store/memory_store.rs
zarrs_zip/CHANGELOG.md
zarrs_zip/Cargo.toml

This is technically a breaking API change for `zarrs_storage`, but stores/user code do not require any changes.

feat!: Add upcasting methods to storage traits

---

CHANGELOG.md
zarrs/src/array/array_bytes_fixed_disjoint_view.rs
zarrs/src/array_subset.rs
zarrs/src/array_subset/iterators.rs
zarrs/src/array_subset/iterators/contiguous_indices_iterator.rs
zarrs/src/array_subset/iterators/contiguous_linearised_indices_iterator.rs

Reverts a trivial optimisation added in 65542ccb0ac5727930a7687c5bd6c2e84e5b5f5e. The original form is required for generic indexers (#52).

refactor: revert contiguous iterator outputs to `(_, u64)`

---

.github/workflows/ci.yml

These are available in `ubuntu-latest`

chore(CI): remove apt install of cmake/clang

---

CHANGELOG.md
zarrs/src/array/array_sync_readable_writable.rs
zarrs/src/array/codec.rs
zarrs/src/array/codec/array_to_array/squeeze.rs
zarrs/src/array/codec/array_to_array/squeeze/squeeze_codec.rs
zarrs/src/array/codec/array_to_array/squeeze/squeeze_partial_decoder.rs
zarrs/src/array/codec/array_to_array/squeeze/squeeze_partial_encoder.rs
zarrs/src/array/codec/array_to_array/transpose.rs
zarrs/src/array/codec/array_to_array/transpose/transpose_codec.rs
zarrs/src/array/codec/array_to_array/transpose/transpose_partial_decoder.rs
zarrs/src/array/codec/array_to_array/transpose/transpose_partial_encoder.rs
zarrs/src/array/codec/array_to_array_partial_decoder_default.rs
zarrs/src/array/codec/array_to_array_partial_encoder_default.rs
zarrs/src/array/codec/array_to_bytes/codec_chain.rs
zarrs/src/array/codec/array_to_bytes/sharding/sharding_codec.rs
zarrs/src/array/codec/array_to_bytes/sharding/sharding_partial_decoder_sync.rs
zarrs/src/array/codec/array_to_bytes/sharding/sharding_partial_encoder.rs
zarrs/src/array/codec/array_to_bytes/vlen_v2/vlen_v2_macros.rs
zarrs/src/array/codec/array_to_bytes_partial_decoder_default.rs
zarrs/src/array/codec/array_to_bytes_partial_encoder_default.rs
zarrs/src/array/codec/bytes_to_bytes_partial_decoder_default.rs
zarrs/src/array/codec/bytes_to_bytes_partial_encoder_default.rs
zarrs/tests/indexer.rs

This is how it should have been done from the start. A combined input/output handle that can do partial encoding and decoding.
Better code reuse amongst encoders/decoders can be introduced later. Async and a few codecs need to be supported before the experimental status can be removed from partial encoding.

refactor: revise partial encoding API

---

zarrs/doc/status/chunk_grids.md
zarrs/doc/status/chunk_key_encodings.md
zarrs/src/array/chunk_grid/rectangular.rs
zarrs/src/array/chunk_grid/regular.rs
zarrs/src/array/chunk_grid/regular_bounded.rs
zarrs/src/array/chunk_key_encoding/default_suffix.rs
zarrs/src/array/codec/array_to_array/reshape.rs

- add experimental warning boxes for default_suffix, regular_bounded, reshape

fix: match chunk grid docs style to codecs

---

CHANGELOG.md
Cargo.toml
zarrs/Cargo.toml
zarrs_data_type/CHANGELOG.md
zarrs_filesystem/CHANGELOG.md
zarrs_http/CHANGELOG.md
zarrs_metadata/CHANGELOG.md
zarrs_metadata_ext/CHANGELOG.md
zarrs_object_store/CHANGELOG.md
zarrs_plugin/CHANGELOG.md
zarrs_registry/CHANGELOG.md
zarrs_registry/Cargo.toml
zarrs_storage/CHANGELOG.md
zarrs_zip/CHANGELOG.md

zarrs: 0.21 -> 0.22
zarrs_data_type: 0.3.2 -> 0.3.3
zarrs_filesystem: 0.2.3 -> 0.3.0
zarrs_http: 0.2.2 -> 0.3.0
zarrs_metadata: 0.5.0 -> 0.6.0
zarrs_metadata_ext: 0.1.1 -> 0.2.0
zarrs_object_store: 0.4.3 -> 0.5.0
zarrs_plugin: 0.2.1 -> 0.2.2
zarrs_registry: 0.1.4 -> 0.1.5
zarrs_storage: 0.3.4 -> 0.4.0
zarrs_zip: 0.2.3 -> 0.3.0

chore: prepare zarrs 0.22.0 release

---

.github/workflows/ci.yml

chore(CI): switch to `macos-15-intel` runner
